# Generated by spaday.cem from components.cem.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Literal

from spaday.catalog import ComponentSchema, PropertySchema
from spaday.component import Child, Component

__all__ = ["SpadayCodemirror"]


class SpadayCodemirror(Component):
    """CodeMirror 6 code editor."""

    tag = "spaday-codemirror"
    schema = ComponentSchema(
        tag="spaday-codemirror",
        class_name="SpadayCodemirror",
        summary="CodeMirror 6 code editor.",
        props=(
            PropertySchema(name="doc", kind="string", choices=(), default="", description="Editor contents."),
            PropertySchema(
                name="language",
                kind="enum",
                choices=("python", "javascript", "json", "markdown", "plain"),
                default="plain",
                description="Syntax mode.",
            ),
            PropertySchema(name="theme", kind="enum", choices=("light", "dark"), default="light", description="Color theme."),
            PropertySchema(name="read_only", kind="boolean", choices=(), default="false", description="Disallow user edits."),
            PropertySchema(name="line_numbers", kind="boolean", choices=(), default="true", description="Show the line-number gutter."),
            PropertySchema(name="tab_size", kind="number", choices=(), default="4", description="Tab width and indent unit, in spaces."),
        ),
        fields=(
            PropertySchema(
                name="selection",
                kind="json",
                choices=(),
                type_text="{ anchor: number; head?: number } | null",
                default=None,
                description="Main selection; head defaults to anchor.",
            ),
            PropertySchema(
                name="remote_cursors",
                kind="json",
                choices=(),
                type_text="{ peer: string; anchor: number; head?: number; label?: string; color?: string }[]",
                default=None,
                description="Remote selections keyed by peer; labels and colors are optional presentation metadata.",
            ),
        ),
        events=("editor-change", "editor-selection"),
        slots=(),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        doc: str | None = None,
        language: Literal["python", "javascript", "json", "markdown", "plain"] | None = None,
        theme: Literal["light", "dark"] | None = None,
        read_only: bool | None = None,
        line_numbers: bool | None = None,
        tab_size: float | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "doc": doc,
                "language": language,
                "theme": theme,
                "read_only": read_only,
                "line_numbers": line_numbers,
                "tab_size": tab_size,
            },
            **props,
        )
